"use client";

import React from "react";
import {
  FileText,
  FileCheck2,
  TrendingDown,
  Cpu,
  BarChart3,
  Download,
  Printer,
} from "lucide-react";

interface StatsCardsProps {
  originalWords: number;
  summaryWords: number;
  reductionPercentage: number;
  model: string;
  summaryText: string;
  keyPoints: string[];
}

export default function StatsCards({
  originalWords,
  summaryWords,
  reductionPercentage,
  model,
  summaryText,
  keyPoints,
}: StatsCardsProps) {
  // Export as Markdown
  const handleExportMarkdown = () => {
    const mdContent = `# Smart Study Notes\n\n` +
      `**Model:** ${model}\n` +
      `**Original Words:** ${originalWords} | **Summary Words:** ${summaryWords} | **Reduction:** ${reductionPercentage}%\n\n` +
      `## Summary\n\n${summaryText}\n\n` +
      `## Key Revision Points\n\n` +
      keyPoints.map((p, i) => `${i + 1}. ${p}`).join("\n") +
      `\n\n---\n*Generated by Smart Study Notes Generator (Python + Generative AI)*\n`;

    const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Study_Notes_${Date.now()}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200/90 shadow-sm p-5 sm:p-6 overflow-hidden transition-all duration-300 hover:shadow-md hover:border-slate-300">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 pb-4 mb-5 border-b border-slate-100">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold">
            <BarChart3 className="w-3.5 h-3.5" />
          </div>
          <h3 className="font-bold text-xs uppercase tracking-wider text-slate-800">
            STATISTICS
          </h3>
        </div>

        {/* Export / Print Tools */}
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleExportMarkdown}
            className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-slate-50 border border-slate-200 text-slate-700 hover:text-blue-600 hover:bg-slate-100 text-xs font-semibold transition-all cursor-pointer"
            title="Download Notes as Markdown file"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export .MD</span>
          </button>

          <button
            type="button"
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-slate-50 border border-slate-200 text-slate-700 hover:text-blue-600 hover:bg-slate-100 text-xs font-semibold transition-all cursor-pointer"
            title="Print or save as PDF"
          >
            <Printer className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Print</span>
          </button>
        </div>
      </div>

      {/* Grid of 4 Stat Metric Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        {/* Stat 1: Original Words */}
        <div className="p-4 rounded-xl bg-slate-50/70 border border-slate-100 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-500 mb-2">
            <span className="text-xs font-semibold uppercase tracking-wider">
              Original Words
            </span>
            <FileText className="w-4 h-4 text-slate-400" />
          </div>
          <div className="text-2xl sm:text-3xl font-extrabold text-slate-900">
            {originalWords}
          </div>
          <span className="text-[11px] text-slate-400 mt-1">Source word count</span>
        </div>

        {/* Stat 2: Summary Words */}
        <div className="p-4 rounded-xl bg-slate-50/70 border border-slate-100 flex flex-col justify-between">
          <div className="flex items-center justify-between text-slate-500 mb-2">
            <span className="text-xs font-semibold uppercase tracking-wider">
              Summary Words
            </span>
            <FileCheck2 className="w-4 h-4 text-blue-500" />
          </div>
          <div className="text-2xl sm:text-3xl font-extrabold text-blue-600">
            {summaryWords}
          </div>
          <span className="text-[11px] text-slate-400 mt-1">Generated length</span>
        </div>

        {/* Stat 3: Reduction */}
        <div className="p-4 rounded-xl bg-emerald-50/50 border border-emerald-100/80 flex flex-col justify-between">
          <div className="flex items-center justify-between text-emerald-700 mb-2">
            <span className="text-xs font-semibold uppercase tracking-wider">
              Reduction
            </span>
            <TrendingDown className="w-4 h-4 text-emerald-600" />
          </div>
          <div className="text-2xl sm:text-3xl font-extrabold text-emerald-700">
            {reductionPercentage}%
          </div>
          <span className="text-[11px] text-emerald-600 font-semibold mt-1">
            {reductionPercentage > 0 ? "Saved study time" : "Equivalent length"}
          </span>
        </div>

        {/* Stat 4: AI Model */}
        <div className="p-4 rounded-xl bg-slate-50/70 border border-slate-100 flex flex-col justify-between col-span-2 sm:col-span-1">
          <div className="flex items-center justify-between text-slate-500 mb-2">
            <span className="text-xs font-semibold uppercase tracking-wider">
              AI Model
            </span>
            <Cpu className="w-4 h-4 text-indigo-500" />
          </div>
          <div className="text-xs sm:text-sm font-bold text-slate-800 font-mono truncate" title={model}>
            {model}
          </div>
          <span className="text-[11px] text-slate-400 mt-1">Hugging Face Engine</span>
        </div>
      </div>
    </div>
  );
}
